server:
  port: 9999

logging:
    level:
      root: info
      com:
        sk: debug
      p4spy: info # query ? 값 출력

spring:
  profiles:
    active:
      - heroku
      -

---
spring:
  profiles: my-local
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
  thymeleaf:
    cache: false



---
spring:
  profiles: heroku
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

---
spring:
  profiles: local
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@172.20.14.206:1521:HOMEDEV
    username: dongbuweb
    password: dongbuweb
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: create # oracle은 drop을 진행 후, create 를 하므로 최초 table 이 없는 경우 drop 오류 발생
    show-sql: true